My_Blog/App_Blog/urls.py
from django.urls import path

from App_Blog import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('create/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<str:slug>', views.blog_details, name='blog_details'),
    path('my-blogs/', views.MyBLogs.as_view(), name='my_blogs'),
    path('edit-blogs/<pk>', views.UpdateBlog.as_view(), name='edit_blogs'),
    path('delete-blogs/<pk>', views.DeleteBlogs.as_view(), name='delete_blogs'),
    path('liked/<pk>', views.liked, name='liked_post'),
    path('unliked/<pk>', views.unliked, name='unliked_post'),

]

My_Blog/my_blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from my_blog_project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Blog/App_Blog/models.py
from django.contrib.auth.models import User
from django.db import models


class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name="Put a Title")
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name="What is on your Mind ")
    blog_image = models.ImageField(upload_to='blog_image', verbose_name='Image')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.blog_title


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment


class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_liked')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_liked')

My_Blog/App_Blog/forms.py
from django import forms

from App_Blog.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

My_Blog/App_Blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from django.views.generic import CreateView, UpdateView, DetailView, DeleteView, TemplateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid

from App_Blog.forms import CommentForm
from App_Blog.models import Blog, Comment, Likes


class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'App_Blog/create_blog.html'
    fields = ['blog_title', 'blog_content', 'blog_image']

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))


class MyBLogs(LoginRequiredMixin, TemplateView):
    template_name = 'App_Blog/my_blogs.html'


class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = 'App_Blog/edit_blog.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('App_Blog:blog_details', kwargs={'slug': self.object.slug})


class DeleteBlogs(LoginRequiredMixin, DeleteView):
    model = Blog
    template_name = 'App_Blog/delete_blogs.html'
    success_url = reverse_lazy('App_Blog:my_blogs')


class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'App_Blog/blog_list.html'
    queryset = Blog.objects.order_by('-publish_date')


@login_required
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form = CommentForm()
    already_liked = Likes.objects.filter(blog=blog, user=request.user)
    if already_liked:
        liked = True
    else:
        liked = False
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug': slug}))

    return render(request, 'App_Blog/blog_details.html',
                  context={'blog': blog, 'comment_form': comment_form, 'liked': liked, })


@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked_post = Likes(blog=blog, user=user)
        liked_post.save()
        return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug': blog.slug}))


@login_required
def unliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug': blog.slug}))

My_Blog/templates/App_Blog/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} {{ blog.blog_title }}{% endblock%}
{% block body %}
<div class="row pt-3">
    <div class="col-sm-6" >
        <h2>{{ blog.blog_title }}</h2>
        <h6> Posted By: @{{ blog.author }}</h6>
        <i><h6> Publish On: @{{ blog.publish_date }}</h6></i>
        <i><h6> Update On: @{{ blog.update_date }}</h6></i>
        <h6>{{ blog.blog_liked.count }} Likes|{{ blog.blog_comment.count }} Comments</h6>
    </div>
    <div class="col-sm-6">
        <img src="/media/{{ blog.blog_image }}" alt="" width="500px">
    </div>
    <p>
    {{ blog.blog_content|linebreaks }}
    </p>
</div>
{% if not liked %}
<a href="{% url 'App_Blog:liked_post' pk=blog.pk %}">
    <i class="fa fa-thumbs-up fa-2x"></i>
</a>
{% else %}
<a href="{% url 'App_Blog:unliked_post' pk=blog.pk %}">
    <i class="fa fa-thumbs-down fa-2x"></i>
</a>
{% endif %}
<div class="row">
    <div class="col-sm-6">
        <hr>
        <h2>Comment: </h2>
        {% for comment in blog.blog_comment.all %}
        <p><a href="#">@{{ comment.user }}</a> {{ comment.comment }}<br>
        <h6>{{ comment.comment_date }}</h6></p>
        {% endfor %}
    </div>
    <div class="col-sm-6">
        <form method="POST">
            {% csrf_token %}
            {{ comment_form|crispy }}
            <input type="submit" value="Submit" class="btn btn-primary btn-sm mt-2">
        </form>
    </div>
</div>
<br>
<br>

{% endblock %}

My_Blog/templates/App_Blog/blog_list.html
{% extends 'base.html'%}
{% load custom_filters %}
{% block title %} Blog List {% endblock%}
{% block body %}
{% for blog in blogs %}
<h2>{{ blog.blog_title}}</h2>
{{ blog.publish_date}}
<div class="row">
    <div class="col-sm-4">
        <img src="/media/{{ blog.blog_image }}" alt="{{ blog.blog_title }}" width="100%">
    </div>
    <div class="col-sm-8">
        <p>{{ blog.blog_content|range_filter|linebreaks }} <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a></p>
        Posted by: <a href="#">{{ blog.author }}</a>
        <h6>{{ blog.blog_liked.count }} Likes|{{ blog.blog_comment.count }} Comments</h6>
    </div>
</div>
<hr>

{% endfor %}
{% endblock %}

My_Blog/templates/App_Blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Create New Blog {% endblock %}
{% block body %}
<h2>Create New Blog :</h2>
<form method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <input type="submit" value="Add Blog" class="btn btn-info btn-sm mt-2">
</form>
{% endblock %}

My_Blog/templates/App_Blog/delete_blogs.html
{% extends 'base.html' %}
{% block title %} Delete {{ blog.blog_title }}{% endblock %}
{%block body %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" class="btn btn-success ">
</form>
{% endblock %}

My_Blog/templates/App_Blog/edit_blog.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title %} Update {{ blog.blog_title }}{% endblock %}
{% block body %}
{% if blog.author == user %}
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <input type="submit" value="Update" class="btn btn-success btn-sm mt-2">
</form>
{% else %}
<div class="alert alert-danger ">
    <p>You are not allowed view this page </p>
</div>
{% endif %}
{% endblock %}

My_Blog/templates/App_Blog/my_blogs.html
{% extends 'base.html'%}
{% load custom_filters %}
{% block title %} {{ user }}{% endblock %}
{% block body %}

{% for blog in user.post_author.all %}
<h2>{{ blog.blog_title}}</h2>
<h6>{{ blog.publish_date}}</h6>
<div class="row">
    <div class="col-sm-4">
        <img src="/media/{{ blog.blog_image }}" alt="{{ blog.blog_title }}" width="100%">
    </div>
    <div class="col-sm-8">
        <p>{{ blog.blog_content|range_filter|linebreaks }} <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a></p>
        <a href="#">Posted by:{{ blog.author }}</a>
        <h6>{{ blog.blog_liked.count }} Likes|{{ blog.blog_comment.count }} Comments</h6>
    </div>
</div>
<a href="{% url 'App_Blog:edit_blogs' pk=blog.pk %}" class="btn btn-success btn-sm mt-2"> Update </a>
<a href="{% url 'App_Blog:delete_blogs' pk=blog.pk %}" class="btn btn-danger btn-sm mt-2"> Delete </a>
<hr>
{% endfor %}
{% endblock %}