My_Blog/App_Blog/urls.py
from django.urls import path

from App_Blog import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('create/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<str:slug>', views.blog_details, name='blog_details'),
    path('my-blogs/', views.MyBLogs.as_view(), name='my_blogs'),
    path('edit-blogs/<pk>', views.UpdateBlog.as_view(), name='edit_blogs'),
    path('delete-blogs/<pk>', views.DeleteBlogs.as_view(), name='delete_blogs'),
    path('liked/<pk>', views.liked, name='liked_post'),
    path('unliked/<pk>', views.unliked, name='unliked_post'),

]

My_Blog/App_Login/urls.py
from django.urls import path

from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('sign_up/', views.sign_up, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('change-profile/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic'),

]

My_Blog/my_blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from my_blog_project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Blog/App_Login/models.py
from django.contrib.auth.models import User
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

My_Blog/App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from App_Login.models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email Address')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class ProfileChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')


class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields =['profile_pic']

My_Blog/App_Login/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from App_Login.forms import SignUpForm, ProfileChangeForm, ProfilePic


def sign_up(request):
    form = SignUpForm
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
    dic = {'form': form, 'registered': registered}
    return render(request, 'App_Login/signup.html', context=dic)


def login_user(request):
    form = AuthenticationForm
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    dict = {'form': form}
    return render(request, 'App_Login/login.html', context=dict)


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def user_profile(request):
    return render(request, 'App_Login/profile.html', context={})


@login_required
def user_change(request):
    current_user = request.user
    form = ProfileChangeForm(instance=current_user)
    if request.method == 'POST':
        form = ProfileChangeForm(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
            form = ProfileChangeForm(instance=current_user)
    return render(request, 'App_Login/change_profile.html', context={'form': form})


def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'App_Login/pass_change.html', context={'form': form, 'changed': changed})


@login_required
def add_pro_pic(request):
    form = ProfilePic
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/add_pro_pic.html', context={'form': form})


@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/add_pro_pic.html', context={'form': form})

My_Blog/templates/App_Login/add_pro_pic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Add Profile Picture{% endblock%}
{% block body %}
<h2>Add Your Profile Picture:</h2>
<form method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <input type="submit" value="Add Picture" class="btn btn-primary btn-sm mt-2">
</form>
{% endblock%}

My_Blog/templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Change Profile {% endblock %}
{% block body %}
<form method="POST">
    {{ form|crispy}}
    {% csrf_token %}
    <input type="submit" value="Change" class="btn btn-warning btn-sm">
</form>

{% endblock %}

My_Blog/templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Login {% endblock %}
{% block body %}
<h2>Login:</h2>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Login" class="btn btn-primary btn-sm mt-2">
</form>
{% endblock %}

My_Blog/templates/App_Login/pass_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Change Password{% endblock %}
{% block body %}
{% if changed %}
    <div class="alert alert-success">
        Password Changed Successfully
    </div>
{% else %}
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <input type="submit" value="Change Password" class="btn btn-warning btn-sm mt-2">
</form>
{% endif %}
{% endblock %}

My_Blog/templates/App_Login/profile.html
{% extends 'base.html' %}
{% block title %}Your Profile{% endblock %}
{% block body %}
<h2>Your Profile: </h2>
{% if user.user_profile %}
<img src="/media/{{ user.user_profile.profile_pic }}" class="rounded-circle" alt="" width="150px">
<br>
<br>
<a href="{% url 'App_Login:change_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
{% else %}
<img src="/media/profile_pics/male-avatar.png" alt="" class="rounded-circle" width="150px">
<br>
<a href="{% url 'App_Login:add_pro_pic'%}" class="btn btn-info btn-sm">Add Profile Picture</a>
{% endif %}
<br>
<br>
<h5>Username : {{ user.username }}</h5>
<h5>Full Name : {{ user.first_name }} {{ user.last_name }}</h5>
<h5>Email : {{ user.email }}</h5>
<br>
<a href="{% url 'App_Login:user_change'%}"class="btn btn-warning btn-sm">Change Profile </a>

{% endblock %}

My_Blog/templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Create New Account {% endblock %}
{% block body %}
{% if registered %}
<div class="alert alert-success">
    Account Created Successfully <a href="{% url 'App_Login:login'%}">Login Here</a>
</div>
{% else %}
<h2>Create New Account: </h2>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-success btn-sm" value="Create Account">
</form>

<p>already have a account?<a href="{% url 'App_Login:login'%}">Login Here </a> </p>
{% endif %}
{% endblock %}