My_Blog/App_Blog/urls.py
from django.urls import path

from App_Blog import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('create/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<str:slug>', views.blog_details, name='blog_details'),
    path('my-blogs/', views.MyBLogs.as_view(), name='my_blogs'),
    path('edit-blogs/<pk>', views.UpdateBlog.as_view(), name='edit_blogs'),
    path('delete-blogs/<pk>', views.DeleteBlogs.as_view(), name='delete_blogs'),
    path('liked/<pk>', views.liked, name='liked_post'),
    path('unliked/<pk>', views.unliked, name='unliked_post'),

]

My_Blog/App_Login/urls.py
from django.urls import path

from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('sign_up/', views.sign_up, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('change-profile/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic'),

]

My_Blog/my_blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from my_blog_project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/13f9557492.js"></script>
    <title>{% block title %} Blogs {% endblock %}</title>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'index'%}">Home</a>
          </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'App_Login:profile'%}">Your Profile </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'App_Blog:create_blog'%}">Add Blog </a>
            </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'App_Blog:my_blogs'%}">My Blogs </a>
            </li>


            <li class="nav-item">
            <a class="nav-link" href="{% url 'App_Login:logout'%}">Logout </a>
            </li>
            {% else %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'App_Login:signup'%}">Sign Up </a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'App_Login:login'%}">Login </a>
          </li>
           {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
        {% block body %}

        {% endblock %}
    </div>
  </body>
</html>